name: dawaya
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.11.5

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  image_picker: ^1.2.2
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  google_maps_flutter: ^2.17.1
  geolocator: ^14.0.3
  cached_network_image: ^3.4.1
  lottie: ^3.3.3
  get: ^4.7.3
  intl: ^0.20.2
  shared_preferences: ^2.5.5
  dio: ^5.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - lib/assets/images/
    - lib/assets/images/onboarding/onboarding1.jpg
    - lib/assets/images/onboarding/onboarding2jpg.jpg
    - lib/assets/images/onboarding/onboarding3.jpg
    - lib/assets/images/onboarding/onboarding4.jpg
    - lib/assets/images/auth/signup.jpg
    - lib/assets/images/auth/login.jpg
    - lib/assets/images/auth/forgetPassword.jpg
    - lib/assets/images/png/
    - lib/assets/images/png/facebook-icon.png
    - lib/assets/images/png/google-icon.png
    - lib/assets/images/auth/resetPassword.jpg
    - lib/assets/images/jpg/pharmacies_logos/
    - lib/assets/images/jpg/pharmacies_logos/ezaby.jpg
    - lib/assets/images/jpg/pharmacies_logos/tarshouby.jpg
    - lib/assets/images/jpg/pharmacies_logos/seif.jpg
    - lib/assets/images/jpg/pharmacies_logos/DrWells.jpg
    - lib/assets/images/jpg/banners/
    - lib/assets/images/jpg/banners/ezaby_banner1.jpeg
    - lib/assets/images/jpg/banners/tarshouby_banner2.jpg
    - lib/assets/images/jpg/banners/seif_banner3.png
    - lib/assets/images/jpg/banners/drWells_banner4.jpg
    - lib/assets/images/jpg/categories_imgs/
    - lib/assets/images/jpg/categories_imgs/pills.jpg
    - lib/assets/images/jpg/categories_imgs/Antibiotics.jpg
    - lib/assets/images/jpg/categories_imgs/Respiratory.jpg
    - lib/assets/images/jpg/categories_imgs/Vitamins.jpg
    - lib/assets/images/jpg/categories_imgs/Hair Care.jpg
    - lib/assets/images/jpg/categories_imgs/Skin Care.jpg
    - lib/assets/images/jpg/products/
    - lib/assets/images/jpg/products/Paracetamol 500mg.jpeg
    - lib/assets/images/jpg/products/Amoxicillin 250mg.jpeg
    - lib/assets/images/jpg/products/Azithromycin 500mg.jpeg
    - lib/assets/images/jpg/products/Vitamin C 1000mg.jpeg
    - lib/assets/images/jpg/products/Vitamin D3 5000IU.jpeg
    - lib/assets/images/jpg/products/Voltaren Gel.jpg
    - lib/assets/images/jpg/products/ketofanGel.jpeg
    - lib/assets/images/jpg/products/Ibuprofen 400mg.jpeg
    - lib/assets/images/jpg/products/cefixime.jpeg
    - lib/assets/images/jpg/products/augmentin1g.jpeg
    - lib/assets/images/jpg/products/multivitamin.jpeg
    - lib/assets/images/jpg/products/omega3.jpeg
    - lib/assets/images/jpg/products/Otrivin Nasal Spray.jpeg
    - lib/assets/images/jpg/products/Ventolin Inhaler.jpeg
    - lib/assets/images/jpg/products/mucosolSyrup.jpeg
    - lib/assets/images/jpg/products/strepsils.jpeg
    - lib/assets/images/jpg/products/vichyDercosShampoo.jpeg
    - lib/assets/images/jpg/products/panthenolHairCream.jpeg
    - lib/assets/images/jpg/products/arganHairSerum.jpeg
    - lib/assets/images/jpg/products/ceraveMoisturizingCream.jpeg
    - lib/assets/images/jpg/products/laRochePosayCleanser.jpeg
    - lib/assets/images/jpg/products/panthenolCream.jpeg
    - lib/assets/images/jpg/products/neutrogenaHydroBoost.jpeg
    - lib/assets/images/jpg/cart/
    - lib/assets/images/jpg/cart/empty cart.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-pack