// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADBZVibnyaZfBp5corQnY48r70Ssazxsc',
    appId: '1:141762125036:web:ae487872863d8f89f519c9',
    messagingSenderId: '141762125036',
    projectId: 'dawaya-ca542',
    authDomain: 'dawaya-ca542.firebaseapp.com',
    storageBucket: 'dawaya-ca542.firebasestorage.app',
    measurementId: 'G-TLNV908KTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNeblesPtjm_y3fSmE21rtNjFUmbEBHQA',
    appId: '1:141762125036:android:c78adde03034a348f519c9',
    messagingSenderId: '141762125036',
    projectId: 'dawaya-ca542',
    storageBucket: 'dawaya-ca542.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHNUv4qNTxDBpOY77QU4zGm97NsPC8e5E',
    appId: '1:141762125036:ios:4cd89ccd9335b666f519c9',
    messagingSenderId: '141762125036',
    projectId: 'dawaya-ca542',
    storageBucket: 'dawaya-ca542.firebasestorage.app',
    iosBundleId: 'com.example.dawaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHNUv4qNTxDBpOY77QU4zGm97NsPC8e5E',
    appId: '1:141762125036:ios:4cd89ccd9335b666f519c9',
    messagingSenderId: '141762125036',
    projectId: 'dawaya-ca542',
    storageBucket: 'dawaya-ca542.firebasestorage.app',
    iosBundleId: 'com.example.dawaya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADBZVibnyaZfBp5corQnY48r70Ssazxsc',
    appId: '1:141762125036:web:822ae7f54db3a6d2f519c9',
    messagingSenderId: '141762125036',
    projectId: 'dawaya-ca542',
    authDomain: 'dawaya-ca542.firebaseapp.com',
    storageBucket: 'dawaya-ca542.firebasestorage.app',
    measurementId: 'G-EL4MVWVG60',
  );
}
